#!/bin/bash
# Test if huffman/unhuffman works on a small file of ASCII symbols
PATH="../:$PATH"
INFILE="resources/image.jpg"
OUTFILE="image.jpg.unhuff"

huffman -c ${INFILE} | unhuffman -c - > ${OUTFILE}
diff -a ${INFILE} ${OUTFILE} &>/dev/null
rc=$?;

rm $OUTFILE;

exit $rc;
