#!/bin/bash
# Test if huffman/unhuffman works on a file of 20 NULL symbols
PATH="../:$PATH"
INFILE="resources/null.txt"
OUTFILE="null.unhuff"

huffman ${INFILE} | unhuffman > ${OUTFILE}
diff -a ${INFILE} ${OUTFILE} &>/dev/null
rc=$?;

rm $OUTFILE;

exit $rc;
