#!/bin/bash
# Test if huffman/unhuffman works on a file of 20 NULL symbols
PATH="../:$PATH"
INFILE="resources/null.txt"
OUTFILE="null.huff"

vopts="--tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes --track-origins=yes --error-exitcode=1"

valgrind $vopts huffman ${INFILE} ${OUTFILE} &>/dev/null
rc=$?;

rm $OUTFILE;

exit $rc;
