#!/bin/bash
# Test if huffman/unhuffman works on a file of 20 NULL symbols
PATH="../:$PATH"
INFILE="resources/null.txt"
OUTFILE="null.huff"

valgrind --error-exitcode=1  huffman ${INFILE} ${OUTFILE} &>/dev/null
rc=$?;

rm $OUTFILE;

exit $rc;
